---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  
  tasks:
    # - name: Copy configuration files to server using templates.
    #   ansible.builtin.template:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.dest }}"
    #     owner: "{{ item.owner }}"
    #     mode: 0644
    #   with_items:
    #     - { src: "files/info.php", dest: "/var/www/{{ user_list }}/", owner: "{{ user_list }}" }
    #     - { src: "files/fpm.conf.j2", dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ user_list }}.conf", owner: "root" }
    #     - { src: "files/http.conf.j2", dest: "/etc/nginx/sites-available/{{ user_list }}-http.conf", owner: "root" }
    #       copy all config files to /tmp/conf_files/
    #       output user_list to file and copy to /tmp/conf_files/ loop:
    # - name: Copy configuration files to server using templates.
    #   ansible.builtin.shell: |
    #     php_version=`php -v|head -1|awk '{print $2}'|head -c -3`
    #     cat user_list | while read line 
    #     do 
    #     for i in $line
    #     do
    #     cp /tmp/conf_files/info.php /var/www/$i
    #     chown -R $i: /var/www/$i
    #     cp /tmp/conf_files/fpm.conf /etc/php/$(php_version)/fpm/pool.d/$i.conf
    #     chown root: /etc/php/$(php_version)/fpm/pool.d/$i.conf
    #     cp /tmp/conf_files/http.conf /etc/nginx/sites-available/$i-http.conf
    #     chown root: /etc/nginx/sites-available/$i-http.conf
    #     done
    #     done 
    #   args:
    #     executable: /bin/bash

    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "files/info.php"
        dest: "/var/www/{{ item.user_list }}/"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ user_list }}"
    
    # - name: Copy fpm.conf to app's fpm pool directory
    #   ansible.builtin.template:
    #     src: "files/fpm.conf.j2"
    #     dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ item }}.conf"
    #     owner: "{{ item }}"
    #     group: "{{ item }}"
    #     mode: '0644'
    #   loop: "{{ user_list }}"

    # - name: Copy http.conf to app's nginx sites-available directory
    #   ansible.builtin.template:
    #     src: "files/http.conf.j2"
    #     dest: "/etc/nginx/sites-available/{{ item }}-http.conf"
    #     owner: "{{ item }}"
    #     group: "{{ item }}"
    #     mode: '0644'
    #   loop: "{{ user_list }}"
    
      
        