---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Create app directories
      ansible.builtin.file:
        path: "{{ item[2] }}/{{ item[0] }}"
        owner: "{{ item[0] }}"
        group: "{{ item[0] }}"
        mode: "{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ user_list }}"
        - [ '0700' ]
        - [ '/var/log/php-fpm/','/var/lib/php/sessions/','/var/www/' ]
          
        
