---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Create app directories
      ansible.builtin.file:
        path: "{{ item.dir_name }}"
        owner: "{{ item.owner }}"
        mode: "{{ item.mode }}"
        state: directory
      with_items:
        - { dir_name: /var/log/php-fpm/{{ user_list }}, mode: '0700', owner: "{{ user_list }}" }
          
        
