---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  
  handlers:
    - include_tasks: handlers/main.yml
  
  tasks:
    - import_tasks: tasks/main.yml

 

