---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Create /srv/users/ directory
      ansible.builtin.file:
        path: "/srv/users/{{ item }}"
        owner: root
        mode: '0755'
        state: directory
      loop: "{{ user_list }}"

    - name: Create app user 
      ansible.builtin.user:
        name: "{{ item }}"
        create_home: true
        home: "/srv/users/{{ item }}"
      loop: "{{ user_list }}"

    - name: Add user www-data to app users' group
      ansible.builtin.user:
        name: www-data
        groups: "{{ user_list }}"
        append: true 

    - name: Create app directories
      ansible.builtin.file:
        path: "{{ item[2] }}/{{ item[0] }}"
        owner: "{{ item[0] }}"
        group: "{{ item[0] }}"
        mode: "{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ user_list }}"
        - [ '0700' ]
        - [ '/var/log/php-fpm/','/var/lib/php/sessions/','/var/www/' ]

    - name: Change /var/www directory permissions
      ansible.builtin.file:
        path: "/var/www/{{ item }}"
        mode: '0755'
        state: directory
      loop: "{{ user_list }}"
       
    - name: Check if www.conf exists 
      ansible.builtin.stat:
        path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
      register: check_file_name

    - name: Rename www.conf to www.conf.default
      ansible.builtin.copy:
        remote_src: true
        src: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
        dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf.default"
      when: check_file_name.stat.exists == true

    - name: Copy configuration files to server using templates.
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        mode: 0644
      with_items:
        - { src: "files/info.php", dest: "/var/www/{{ user_list }}/", owner: "{{ user_list }}" }
        - { src: "files/fpm.conf.j2", dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ user_list }}.conf", owner: "root" }
        - { src: "files/http.conf.j2", dest: "/etc/nginx/sites-available/{{ user_list }}-http.conf", owner: "root" }

    - name: Copy configuration files to server using templates.
      ansible.builtin.template:
        src: "{{ item[1] }}"
        dest: "{{ item[2] }}"
        owner: "{{ item.owner }}"
        mode: 0644
      with_nested:
        - "{{ user_list }}"
        - [ 'files/info.php','files/fpm.conf.j2','files/http.conf.j2'  ]
        - [ '/var/www/','/etc/php/{{ php_version }}/fpm/pool.d/.conf','/etc/nginx/sites-available/-http.conf' ]
        - { src: "", dest: "/{{ user_list }}/", owner: "{{ user_list }}" }
        - { src: "", dest: "{{ user_list }}", owner: "root" }
        - { src: "", dest: "{{ user_list }}", owner: "root" }

    - name: Create a symbolic link from sites-available configuration to sites-enabled configuration
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ user_list }}-http.conf"
        dest: "/etc/nginx/sites-enabled/{{ user_list }}-http.conf"
        state: link
      notify: 
        - reload nginx
        - restart php-fpm
