---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Check if www.conf exists 
      ansible.builtin.stat:
        path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
      register: check_file_name

    - name: Rename www.conf to www.conf.default
      ansible.builtin.copy:
        remote_src: true
        src: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
        dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf.default"
      when: check_file_name.stat.exists == true

    - name: Delete original www.conf file
      ansible.builtin.file:
        path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
        state: absent
      when: check_file_name.stat.exists 

  # vars:
  #   file_paths:
  #     - file_src: "templates/info.php"
  #     - file_src: "templates/fpm.conf.j2"
  #     - file_src: "templates/http.conf.j2"
  #     - file_dest: "/var/www/{{ item.user }}/"
  #       file_owner: "{{ item.user }}"
  #     - file_dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ item.user }}.conf"
  #       file_owner: "root"
  #     - file_dest: "/etc/nginx/sites-available/{{ item.user }}-http.conf"
  #       file_owner: "root"

  # tasks:
  #   - name: Copy test php page to app directory
  #     ansible.builtin.template:
  #       src: "{{ file_src }}"
  #       dest: "{{ file_dest }}"
  #       mode: '0644'
  #       owner: "{{ file_owner }}"
  #     loop: "{{ file_paths | zip(app_username) }}"
         


      



