---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  vars:
    file_paths:
      - file_src: "templates/info.php"
      - file_src: "templates/fpm.conf.j2"
      - file_src: "templates/http.conf.j2"
      - file_dest: "/var/www/{{ lookup('app_username', user) }}/"
        file_owner: "{{ lookup('app_username', user) }}"
      - file_dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ lookup('app_username', user) }}.conf"
        file_owner: "root"
      - file_dest: "/etc/nginx/sites-available/{{ lookup('app_username', user) }}-http.conf"
        file_owner: "root"

  tasks:
    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "{{ file_src }}"
        dest: "{{ file_dest }}"
        mode: '0644'
        owner: "{{ file_owner }}"
      loop: [ "{{ app_username }}","{{ file_paths }}" ]
         


      



