---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  vars:
    file_paths:
      - file_src: "files/info.php"
      - file_src: "files/fpm.conf.j2"
      - file_src: "files/http.conf.j2"
      - file_dest: "/var/www/{{ item.user }}/"
        file_owner: "{{ item.user }}"
      - file_dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ item.user }}.conf"
        file_owner: "root"
      - file_dest: "/etc/nginx/sites-available/{{ item.user }}-http.conf"
        file_owner: "root"

  tasks:
    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "{{ file_src }}"
        dest: "{{ file_dest }}"
        mode: '0644'
        owner: "{{ item.file_owner }}"
      loop: 
        - "{{ app_username }}"
        - "{{ file_paths }}"
      # loop: [ "{{ app_username }}","{{ file_paths }}" ]

      



