---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
        mode: '0644'
      with_items: 
        - "{{ app_username }}"
        - { src: "files/info.php", "files/fpm.conf.j2", "files/http.conf.j2" }
        - { dest: "/var/www/{{ item.user }}/", "/etc/php/{{ php_version }}/fpm/pool.d/{{ item.user }}.conf", "/etc/nginx/sites-available/{{ item.user }}-http.conf" }