---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml

  tasks:

    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "{{ item[0] }}"
        dest: "{{ item[1] }}"
        mode: '0644'
      with_nested: 
        - [ 'files/info.php','files/fpm.conf.j2','files/http.conf.j2' ]
        - [ '/var/www/','/etc/php/{{ php_version }}/fpm/pool.d/','/etc/nginx/sites-available/' ]

