---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  vars:
    - file_src: "files/info.php"
    - file_dest: "/var/www/{{ item.user }}"

  tasks:
    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "{{ item.file_src }}"
        dest: "{{ item.file_dest }}"
        mode: '0644'
      



