---
- name: Playbook to configure a PHP app on a LEMP stack 
  hosts: all
  remote_user: emmanuel.apreko
  become: true
  vars_files:
    - vars/main.yml
  vars:
    file_src: "files/info.php"
    file_dest: "/var/www/{{ php_version }}"

  tasks:
    - name: Copy test php page to app directory
      ansible.builtin.template:
        src: "{{ file_src }}"
        dest: "{{ file_dest }}"
        mode: '0644'
      loop: "{{ app_username }}"

      



