---
- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
    changed_when: True

- name: restart php-fpm 
  ansible.builtin.service:
    name: php{{php_version }}-fpm
    state: restarted
    changed_when: True
