---
- name: validate nginx configuration
  command: "nginx -t"

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: validate fpm configuration
  command: php-fpm{{php_version }} -t

- name: restart php-fpm 
  ansible.builtin.service:
    name: php{{php_version }}-fpm
    state: restarted


